# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bram_bd/bram_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_bd || ORIG_REF_NAME==bram_bd} -quiet] -quiet

# IP: bd/bram_bd/ip/bram_bd_processing_system7_0_0/bram_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_bd_processing_system7_0_0 || ORIG_REF_NAME==bram_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/bram_bd/ip/bram_bd_axi_bram_ctrl_0_0/bram_bd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==bram_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/bram_bd/ip/bram_bd_blk_mem_gen_0_0/bram_bd_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==bram_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/bram_bd/ip/bram_bd_rst_ps7_0_100M_0/bram_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==bram_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bram_bd/ip/bram_bd_axi_interconnect_0_1/bram_bd_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_bd_axi_interconnect_0_1 || ORIG_REF_NAME==bram_bd_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/bram_bd/ip/bram_bd_auto_pc_0/bram_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_bd_auto_pc_0 || ORIG_REF_NAME==bram_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/bram_bd/bram_bd_ooc.xdc
