# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/data0_bd/data0_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd || ORIG_REF_NAME==data0_bd} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_processing_system7_0_0/data0_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_processing_system7_0_0 || ORIG_REF_NAME==data0_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_proc_sys_reset_0_0/data0_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==data0_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_axi_dma_0_0/data0_bd_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_axi_dma_0_0 || ORIG_REF_NAME==data0_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_ps7_0_axi_periph_0/data0_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==data0_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_axi_smc_1/data0_bd_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_axi_smc_1 || ORIG_REF_NAME==data0_bd_axi_smc_1} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_xlconcat_0_0/data0_bd_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_xlconcat_0_0 || ORIG_REF_NAME==data0_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_axis_data_fifo_0_0/data0_bd_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_axis_data_fifo_0_0 || ORIG_REF_NAME==data0_bd_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/data0_bd/ip/data0_bd_auto_pc_0/data0_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data0_bd_auto_pc_0 || ORIG_REF_NAME==data0_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/data0_bd/data0_bd_ooc.xdc
