# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/karanraj/Documents/bramtest/bramtest.srcs/sources_1/bd/bram_bd/ip/bram_bd_axi_bram_ctrl_0_0/bram_bd_axi_bram_ctrl_0_0.xci
# IP: The module: 'bram_bd_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karanraj/Documents/bramtest/bramtest.srcs/sources_1/bd/bram_bd/ip/bram_bd_axi_bram_ctrl_0_0/bram_bd_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_bd_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/karanraj/Documents/bramtest/bramtest.srcs/sources_1/bd/bram_bd/ip/bram_bd_axi_bram_ctrl_0_0/bram_bd_axi_bram_ctrl_0_0.xci
# IP: The module: 'bram_bd_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karanraj/Documents/bramtest/bramtest.srcs/sources_1/bd/bram_bd/ip/bram_bd_axi_bram_ctrl_0_0/bram_bd_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_bd_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
